### PR TITLE
Add Legendary Divinations and Wing 6 Killproofs

### PR DESCRIPTION
**Pull request by fanonwue**
I added the new Legendary Divinations and the new KP for Wing 6.

The menu structure also changed a bit, Fractals is now at 1, the raid wings start at 2, so wing 6 is accessed by typing 7.

### CODE REVIEW

**Comment by hellmaine** [comment]
> I added the new Legendary Divinations and the new KP for Wing 6.
> 
> The menu structure also changed a bit, Fractals is now at 1, the raid wings start at 2, so wing 6 is accessed by typing 7.

So i installed pyhton and pyinstaller to make the exe, i copied the code from here and put it in pyhton then run cmd and pyinstaller using --onefile and the .py file i copied from here and after its done when i click on the exe file it just opens for a second and then closes :// what did i wrong, It's my first time doing stuff like this...

Or can you send me your working new version please?

**Comment by ArisenDrake** [comment]
I assumed that this would get merged sooner.

Yes I have a working version, I will add it to my repo when I come home today.

**Comment by fanonwue** [comment]
I added a release to my fork including the binary .exe version I am using, please see here: https://github.com/ArisenDrake/Gw2ChatCodeBuddy/releases/tag/3.8

It's working perfectly for me, so please tell me if it does not for you.

And regarding pyinstaller, what command line options are you using? Have you tried using --onefile (it bundles all dependencies into one package, please refer to https://pythonhosted.org/PyInstaller/usage.html#what-to-generate)?

A bit OT: No problem if you have no experience of course, while I am a software developer I never used python before. First time using GitHub as well lul.

**Comment by m10x** [comment]
@ArisenDrake

Thanks for the improvements! I'm sorry, that I didn't notice this earlier!
I got one question, why did you remove the update check?

**Review by m10x — APPROVED** [review]

**Comment by m10x** [comment]
@hellmaine It doesn't work, because you need to install all of the used python dependencies first, before making the .exe. If you open cmd and start the exe. from there, it should show you which ones are missing. :)

**Pull request merged**
